### PR TITLE
README update

### PR DESCRIPTION
**Pull request by flyingmachine**
Trying to prep this for the community release :)

### CODE REVIEW

**Comment by cap10morgan** [comment]
This looks like great content, but I’m not sure this README is the best place for it. Need to think a little about community packaging and distribution. We may want a new repo for that. There will be other future components in the “standard” Fluree artifact that most open source users will likely start with.

**Comment by flyingmachine** [comment]
I get what you mean. I'm unsure about how to adequately serve both external users and internal devs. Happy to chat about it more some time if you'd like. Some of the factors I'm considering:

* Who are the audiences, and what questions do they need answered?
  * Fluree employees - need to onboard
  * Community devs
  * Customers who need to get started
  * Potential customers
* As READMEs are essentially landing pages on GitHub, who's the main audience?

My thinking is to cater to people who have the least familiarity with the Fluree ecosystem. I was thinking that for internal employees and community devs we could create a more concise developer guide under `/docs` or something.

Anyway thanks for considering this, this is often how I collaborate - just throw up a PR for discussion, as I find having something concrete helps focus the discussion.

**Comment by cap10morgan** [comment]
@flyingmachine That all sounds right. We're discussing creating a good place for this kind of thing to go in Slack. Might be a new GitHub repo. I'll keep you posted.

**Comment by cap10morgan** [comment]
@flyingmachine I created a new repo where things like this can live: https://github.com/fluree/core

There's not much there yet but feel free to push a README along these lines there!

**Pull request closed without merging**
